### PR TITLE
Implement proper UndecorateNick Support

### PR DESCRIPTION
**Pull request by Oppossome**
Derped up last time

### CODE REVIEW

**Comment by loserVEVO** [comment]
why didnt you just make a new commit to the old PR

**Comment by loserVEVO** [comment]
this is why girls dont code

**Comment by Noiwex** [comment]
lol datamats

**Comment by KrakenZ** [comment]
Bg X5 ctv6c😚,8v9f WX b

**Comment by Zeni44** [comment]
very nice comment

**Comment by PotcFdk** [comment]
Welcome to 20 years ago.

**Pull request merged**
