### PR TITLE
Fix ability to server luarun using SteamID spoof

### PR DESCRIPTION
**Pull request by klen-list**
There is a way to steal a player's authorization token and use it to access any privileges under his SteamID

### CODE REVIEW

**Comment by Python1320** [comment]
This should not be possible anymore since the game servers wait for full authorization on join, but maybe something changed?
In addition IsAdmin checks should have incorporated that function check themselves already.

**Comment by klen-list** [comment]
the servers are waiting for full authorization only if one of the real players is on the server, if you go to an empty server, the check will be skipped and only after a minute you will be kicked with the steam connect error

**Comment by klen-list** [comment]
Unfortunately, isAdmin checks do not verify authentication, they only return the result of GetNWString
Given that there is no authentication check in many popular admin systems like ULX, obtaining admin privileges using token spoof becomes a simple task

**Comment by Python1320** [comment]
This should definitely then also be also fixed in ULX/ULib because AFAIK those admin mods also have a run lua command

**Pull request merged**
